# Generated by Django 4.1.6 on 2023-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emailID', models.CharField(max_length=200, unique=True)),
                ('iscustomer', models.BooleanField(default=True)),
                ('Name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=15)),
                ('GST', models.CharField(max_length=16)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
    ]
