# Generated by Django 4.1.6 on 2023-03-03 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creditcardnumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('cvvnumber', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
