# Generated by Django 4.1.6 on 2023-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymentsstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=200)),
                ('Restaturantname', models.CharField(max_length=200)),
                ('orderdetails', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=200)),
                ('totalcost', models.CharField(max_length=50)),
            ],
        ),
    ]
