# Generated by Django 4.1.6 on 2023-03-04 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstore',
            old_name='orderdetails',
            new_name='ItemList',
        ),
        migrations.RenameField(
            model_name='orderstore',
            old_name='Restaturantname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderstore',
            old_name='totalcost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderstore',
            name='customername',
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='GST',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='Location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='MobileNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentsstore',
            name='creditcardnumber',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
